FROM dolfinx/dolfinx:v0.6.0-r1

RUN python3 -m pip install --no-cache-dir -U pip && \
    python3 -m pip install --no-cache-dir cppyy pdbpp

RUN git clone --depth=1 https://github.com/algoim/algoim.git /tmp/algoim && \
    cp -r /tmp/algoim/algoim /usr/local/include/ && \
    rm -rf /tmp/algoim

RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
      git ccache parallel && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY customquad/call_basix.h /usr/local/include/call_basix.h
COPY customquad/call_basix.cpp /tmp/call_basix.cpp
RUN g++ -std=c++20 -fPIC -shared /tmp/call_basix.cpp -o /usr/local/lib/libcall_basix.so \
      -L/usr/local/lib -L/usr/local/dolfinx-real/lib -lbasix && ldconfig

WORKDIR /work
SHELL ["/bin/bash", "-lc"]
