FROM dolfinx/dolfinx:v0.6.0-r1

RUN python3 -m pip install --no-cache-dir -U pip && \
    python3 -m pip install --no-cache-dir cppyy pdbpp

RUN git clone --depth=1 https://github.com/algoim/algoim.git /tmp/algoim && \
    cp -r /tmp/algoim/algoim /usr/local/include/ && \
    rm -rf /tmp/algoim

RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
      git ccache parallel && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /work
SHELL ["/bin/bash", "-lc"]
